"""modelos iniciais

Revision ID: b6e1a15ba443
Revises: 
Create Date: 2026-07-28 10:04:48.278643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e1a15ba443'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semestres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semestre_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('turma', sa.String(length=10), nullable=False),
    sa.Column('carga_horaria', sa.Integer(), nullable=True),
    sa.Column('aulas_previstas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semestre_id', 'codigo', 'turma', name='uq_disciplina_semestre_codigo_turma')
    )
    op.create_table('alunos_disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('faltas_sigaa', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disciplina_id', 'matricula', name='uq_aluno_disciplina_matricula')
    )
    op.create_table('aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('conteudo', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disciplina_id', 'data', name='uq_aula_disciplina_data')
    )
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('aluno_disciplina_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_disciplina_id'], ['alunos_disciplina.id'], ),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avaliacao_id', 'aluno_disciplina_id', name='uq_nota_avaliacao_aluno')
    )
    op.create_table('presencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('aluno_disciplina_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['aluno_disciplina_id'], ['alunos_disciplina.id'], ),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aula_id', 'aluno_disciplina_id', name='uq_presenca_aula_aluno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presencas')
    op.drop_table('notas')
    op.drop_table('avaliacoes')
    op.drop_table('aulas')
    op.drop_table('alunos_disciplina')
    op.drop_table('disciplinas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('semestres')
    # ### end Alembic commands ###
